### ISSUE TITLE
How do you make the client?

### ISSUE THREAD

**Issue by pjbreizh** [I00000/ISSUES#12]
no gulp file...
I saw this webpack stuff, but what command to generate bundle and vendor?

**Comment by I00000** [comment]
https://raw.githubusercontent.com/I00000/ISSUES/master/12/userId/332f3f3b-cc06-4904-898e-5a32d67d779b.JPG

**Comment by I00000** [comment]
cd client
npm run debug

**Comment by pjbreizh** [comment]
solved!
